import os

L=chr(60); G=chr(62); B=chr(123); E=chr(125); D=chr(36); Q=chr(39); BQ=chr(96); SP=' '

def st(n,a=''): return L+n+(SP+a if a else'')+SP+'/'+G
def ot(n,a=''): return L+n+(SP+a if a else'')+G
def ct(n): return L+'/'+n+G

path=r'c:\Users\nerdy\CascadeProjects\TestBB\frontend\src\pages\ListsPage.jsx'
c=[]

c.append("import { useState } from 'react'")
c.append("import { Link } from 'react-router-dom'")
c.append("import {")
c.append("  List, Plus, X, Pencil, Trash2, Sparkles, Copy,")
c.append("  TrendingUp, Brain, Cpu, Zap, Globe, Shield,")
c.append("  BarChart3, Landmark, Fuel, Heart,")
c.append("} from 'lucide-react'")
c.append("import {")
c.append("  getLists, createList, deleteList, renameList,")
c.append("  removeFromList, addToList,")
c.append("} from '../store/pins'")
c.append("")
c.append("const SUGGESTED_LISTS = [")
c.append("  {")
c.append("    id: 'ai-leaders',")
c.append("    name: 'AI Leaders',")
c.append("    description: 'Top companies driving artificial intelligence innovation',")
c.append("    icon: 'Brain',")
c.append("    items: [")
c.append("      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock' },")
c.append("      { symbol: 'MSFT', name: 'Microsoft', type: 'stock' },")
c.append("      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock' },")
c.append("      { symbol: 'META', name: 'Meta Platforms', type: 'stock' },")
c.append("      { symbol: 'AMZN', name: 'Amazon', type: 'stock' },")
c.append("      { symbol: 'TSM', name: 'TSMC', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'ai-infrastructure',")
c.append("    name: 'AI Infrastructure & Chips',")
c.append("    description: 'Semiconductor and cloud companies powering AI workloads',")
c.append("    icon: 'Cpu',")
c.append("    items: [")
c.append("      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock' },")
c.append("      { symbol: 'AMD', name: 'AMD', type: 'stock' },")
c.append("      { symbol: 'AVGO', name: 'Broadcom', type: 'stock' },")
c.append("      { symbol: 'MRVL', name: 'Marvell Technology', type: 'stock' },")
c.append("      { symbol: 'ARM', name: 'ARM Holdings', type: 'stock' },")
c.append("      { symbol: 'MU', name: 'Micron Technology', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'ai-software',")
c.append("    name: 'AI Software & Applications',")
c.append("    description: 'Companies building AI-powered software products',")
c.append("    icon: 'Sparkles',")
c.append("    items: [")
c.append("      { symbol: 'PLTR', name: 'Palantir', type: 'stock' },")
c.append("      { symbol: 'SNOW', name: 'Snowflake', type: 'stock' },")
c.append("      { symbol: 'CRM', name: 'Salesforce', type: 'stock' },")
c.append("      { symbol: 'ADBE', name: 'Adobe', type: 'stock' },")
c.append("      { symbol: 'NOW', name: 'ServiceNow', type: 'stock' },")
c.append("      { symbol: 'PANW', name: 'Palo Alto Networks', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'magnificent-7',")
c.append("    name: 'Magnificent 7',")
c.append("    description: 'The seven mega-cap tech stocks driving market returns',")
c.append("    icon: 'Zap',")
c.append("    items: [")
c.append("      { symbol: 'AAPL', name: 'Apple', type: 'stock' },")
c.append("      { symbol: 'MSFT', name: 'Microsoft', type: 'stock' },")
c.append("      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock' },")
c.append("      { symbol: 'AMZN', name: 'Amazon', type: 'stock' },")
c.append("      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock' },")
c.append("      { symbol: 'META', name: 'Meta Platforms', type: 'stock' },")
c.append("      { symbol: 'TSLA', name: 'Tesla', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'faang-plus',")
c.append("    name: 'FAANG+',")
c.append("    description: 'Classic FAANG stocks plus emerging tech leaders',")
c.append("    icon: 'TrendingUp',")
c.append("    items: [")
c.append("      { symbol: 'META', name: 'Meta', type: 'stock' },")
c.append("      { symbol: 'AAPL', name: 'Apple', type: 'stock' },")
c.append("      { symbol: 'AMZN', name: 'Amazon', type: 'stock' },")
c.append("      { symbol: 'NFLX', name: 'Netflix', type: 'stock' },")
c.append("      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock' },")
c.append("      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'dividend-kings',")
c.append("    name: 'Dividend Kings',")
c.append("    description: '50+ years of consecutive dividend increases',")
c.append("    icon: 'Landmark',")
c.append("    items: [")
c.append("      { symbol: 'JNJ', name: 'Johnson & Johnson', type: 'stock' },")
c.append("      { symbol: 'KO', name: 'Coca-Cola', type: 'stock' },")
c.append("      { symbol: 'PG', name: 'Procter & Gamble', type: 'stock' },")
c.append("      { symbol: 'MMM', name: '3M', type: 'stock' },")
c.append("      { symbol: 'CL', name: 'Colgate-Palmolive', type: 'stock' },")
c.append("      { symbol: 'EMR', name: 'Emerson Electric', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'clean-energy',")
c.append("    name: 'Clean Energy',")
c.append("    description: 'Solar, wind, EV, and renewable energy leaders',")
c.append("    icon: 'Fuel',")
c.append("    items: [")
c.append("      { symbol: 'TSLA', name: 'Tesla', type: 'stock' },")
c.append("      { symbol: 'ENPH', name: 'Enphase Energy', type: 'stock' },")
c.append("      { symbol: 'FSLR', name: 'First Solar', type: 'stock' },")
c.append("      { symbol: 'NEE', name: 'NextEra Energy', type: 'stock' },")
c.append("      { symbol: 'RIVN', name: 'Rivian', type: 'stock' },")
c.append("      { symbol: 'PLUG', name: 'Plug Power', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'cybersecurity',")
c.append("    name: 'Cybersecurity',")
c.append("    description: 'Companies protecting digital infrastructure',")
c.append("    icon: 'Shield',")
c.append("    items: [")
c.append("      { symbol: 'CRWD', name: 'CrowdStrike', type: 'stock' },")
c.append("      { symbol: 'PANW', name: 'Palo Alto Networks', type: 'stock' },")
c.append("      { symbol: 'ZS', name: 'Zscaler', type: 'stock' },")
c.append("      { symbol: 'FTNT', name: 'Fortinet', type: 'stock' },")
c.append("      { symbol: 'S', name: 'SentinelOne', type: 'stock' },")
c.append("      { symbol: 'NET', name: 'Cloudflare', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'healthcare-innovation',")
c.append("    name: 'Healthcare Innovation',")
c.append("    description: 'Biotech and healthcare technology disruptors',")
c.append("    icon: 'Heart',")
c.append("    items: [")
c.append("      { symbol: 'LLY', name: 'Eli Lilly', type: 'stock' },")
c.append("      { symbol: 'UNH', name: 'UnitedHealth', type: 'stock' },")
c.append("      { symbol: 'ISRG', name: 'Intuitive Surgical', type: 'stock' },")
c.append("      { symbol: 'DXCM', name: 'DexCom', type: 'stock' },")
c.append("      { symbol: 'MRNA', name: 'Moderna', type: 'stock' },")
c.append("      { symbol: 'VEEV', name: 'Veeva Systems', type: 'stock' },")
c.append("    ],")
c.append("  },")
c.append("  {")
c.append("    id: 'global-etfs',")
c.append("    name: 'Global Diversification ETFs',")
c.append("    description: 'Low-cost ETFs for broad market exposure',")
c.append("    icon: 'Globe',")
c.append("    items: [")
c.append("      { symbol: 'SPY', name: 'S&P 500 ETF', type: 'etf' },")
c.append("      { symbol: 'QQQ', name: 'Nasdaq 100 ETF', type: 'etf' },")
c.append("      { symbol: 'VTI', name: 'Total Stock Market', type: 'etf' },")
c.append("      { symbol: 'VXUS', name: 'International Stocks', type: 'etf' },")
c.append("      { symbol: 'BND', name: 'Total Bond Market', type: 'etf' },")
c.append("      { symbol: 'GLD', name: 'Gold ETF', type: 'etf' },")
c.append("    ],")
c.append("  },")
c.append("]")
c.append("")
c.append("const ICON_MAP = { Brain, Cpu, Sparkles, Zap, TrendingUp, Landmark, Fuel, Shield, Heart, Globe }")
c.append("")
c.append("export default function ListsPage() {")
c.append("  const [lists, setLists] = useState(getLists())")
c.append("  const [activeTab, setActiveTab] = useState('my-lists')")
c.append("  const [showNewList, setShowNewList] = useState(false)")
c.append("  const [newListName, setNewListName] = useState('')")
c.append("  const [editingList, setEditingList] = useState(null)")
c.append("  const [copiedId, setCopiedId] = useState(null)")
c.append("")
c.append("  const handleCreateList = () => {")
c.append("    if (!newListName.trim()) return")
c.append("    const updated = createList(newListName.trim())")
c.append("    setLists(updated)")
c.append("    setNewListName('')")
c.append("    setShowNewList(false)")
c.append("  }")
c.append("")
c.append("  const handleDeleteList = (id) => {")
c.append("    const updated = deleteList(id)")
c.append("    setLists(updated)")
c.append("  }")
c.append("")
c.append("  const handleRenameList = (id, name) => {")
c.append("    if (!name.trim()) return")
c.append("    const updated = renameList(id, name.trim())")
c.append("    setLists(updated)")
c.append("    setEditingList(null)")
c.append("  }")
c.append("")
c.append("  const handleRemoveFromList = (listId, symbol) => {")
c.append("    const updated = removeFromList(listId, symbol)")
c.append("    setLists(updated)")
c.append("  }")
c.append("")
c.append("  const handleCopySuggested = (suggested) => {")
c.append("    const updated = createList(suggested.name)")
c.append("    const newList = updated[updated.length - 1]")
c.append("    let latestLists = updated")
c.append("    suggested.items.forEach(item => {")
c.append("      latestLists = addToList(newList.id, item)")
c.append("    })")
c.append("    setLists(latestLists)")
c.append("    setCopiedId(suggested.id)")
c.append("    setTimeout(() => setCopiedId(null), 1500)")
c.append("  }")
c.append("")
c.append("  const tabs = [")
c.append("    { id: 'my-lists', label: 'My Lists' },")
c.append("    { id: 'suggested', label: 'Suggested Lists' },")
c.append("  ]")
c.append("")
c.append("  return (")
c.append("    "+ot("div",'className="space-y-6"'))
c.append("      {/* Header */}")
c.append("      "+ot("div",'className="flex items-center justify-between"'))
c.append("        "+ot("div"))
c.append("          "+ot("h1",'className="text-2xl font-bold text-white flex items-center gap-2"'))
c.append("            "+st("List",'className="w-7 h-7 text-primary-400"'))
c.append("            Lists")
c.append("          "+ct("h1"))
c.append("          "+ot("p",'className="text-sm text-gray-400 mt-1"')+"Create, manage, and discover curated stock lists"+ct("p"))
c.append("        "+ct("div"))
c.append("        "+ot("button",'onClick={() => { setActiveTab('+Q+'my-lists'+Q+'); setShowNewList(true) }} className="flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-lg bg-primary-600 text-white hover:bg-primary-500 transition-colors"'))
c.append("          "+st("Plus",'className="w-4 h-4"'))
c.append("          New List")
c.append("        "+ct("button"))
c.append("      "+ct("div"))
c.append("")
c.append("      {/* Tabs */}")
c.append("      "+ot("div",'className="flex gap-1 border-b border-surface-700/50"'))
c.append("        {tabs.map((tab) => (")
c.append("          "+ot("button",'key={tab.id} onClick={() => setActiveTab(tab.id)} className={'+BQ+'px-5 py-2.5 text-sm font-medium border-b-2 transition-colors ${activeTab === tab.id ? '+Q+'border-primary-400 text-primary-300'+Q+' : '+Q+'border-transparent text-gray-400 hover:text-gray-200'+Q+'}'+BQ+'}'))
c.append("            {tab.label}")
c.append("          "+ct("button"))
c.append("        ))}")
c.append("      "+ct("div"))
c.append("")
c.append("      {/* My Lists Tab */}")
c.append("      {activeTab === 'my-lists' && (")
c.append("        "+ot("div",'className="space-y-4"'))
c.append("          {/* New list input */}")
c.append("          {showNewList && (")
c.append("            "+ot("div",'className="card flex items-center gap-2"'))
c.append("              "+ot("input",'type="text" value={newListName} onChange={(e) => setNewListName(e.target.value)} onKeyDown={(e) => e.key === '+Q+'Enter'+Q+' && handleCreateList()} placeholder="List name (e.g., Growth Picks, AI Watchlist)..." className="input-field flex-1 text-sm" autoFocus'))
c.append("              "+ct("input"))
c.append("              "+ot("button",'onClick={handleCreateList} className="btn-primary text-xs px-3 py-1.5"')+"Create"+ct("button"))
c.append("              "+ot("button",'onClick={() => { setShowNewList(false); setNewListName('+Q+Q+') }} className="p-1.5 text-gray-400 hover:text-white"'))
c.append("                "+st("X",'className="w-4 h-4"'))
c.append("              "+ct("button"))
c.append("            "+ct("div"))
c.append("          )}")
c.append("")
c.append("          {lists.length > 0 ? (")
c.append("            "+ot("div",'className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4"'))
c.append("              {lists.map((list) => (")
c.append("                "+ot("div",'key={list.id} className="card"'))
c.append("                  "+ot("div",'className="flex items-center justify-between mb-3"'))
c.append("                    {editingList === list.id ? (")
c.append("                      "+ot("input",'type="text" defaultValue={list.name} onBlur={(e) => handleRenameList(list.id, e.target.value)} onKeyDown={(e) => e.key === '+Q+'Enter'+Q+' && handleRenameList(list.id, e.target.value)} className="input-field text-sm flex-1 mr-2" autoFocus'))
c.append("                      "+ct("input"))
c.append("                    ) : (")
c.append("                      "+ot("h3",'className="text-sm font-semibold text-white"')+"{list.name}"+ct("h3"))
c.append("                    )}")
c.append("                    "+ot("div",'className="flex items-center gap-1"'))
c.append("                      "+ot("button",'onClick={() => setEditingList(editingList === list.id ? null : list.id)} className="p-1 rounded hover:bg-surface-600 text-gray-500 hover:text-white transition-colors"'))
c.append("                        "+st("Pencil",'className="w-3.5 h-3.5"'))
c.append("                      "+ct("button"))
c.append("                      "+ot("button",'onClick={() => handleDeleteList(list.id)} className="p-1 rounded hover:bg-surface-600 text-gray-500 hover:text-red-400 transition-colors"'))
c.append("                        "+st("Trash2",'className="w-3.5 h-3.5"'))
c.append("                      "+ct("button"))
c.append("                    "+ct("div"))
c.append("                  "+ct("div"))
c.append("")
c.append("                  {list.items.length === 0 ? (")
c.append("                    "+ot("p",'className="text-xs text-gray-500 py-4 text-center"')+"No items yet. Add stocks from the stock detail page or copy a suggested list."+ct("p"))
c.append("                  ) : (")
c.append("                    "+ot("div",'className="space-y-1.5 max-h-56 overflow-y-auto"'))
c.append("                      {list.items.map((item) => (")
c.append("                        "+ot("div",'key={item.symbol} className="flex items-center justify-between py-1.5 px-2 rounded-lg hover:bg-surface-700/50 group"'))
c.append("                          "+ot("Link",'to={'+BQ+'/stock/${item.symbol}'+BQ+'} className="flex items-center gap-2 flex-1"'))
c.append("                            "+ot("span",'className="font-mono text-xs font-bold text-white"')+"{item.symbol}"+ct("span"))
c.append("                            "+ot("span",'className="text-[11px] text-gray-500 truncate"')+"{item.name}"+ct("span"))
c.append("                          "+ct("Link"))
c.append("                          "+ot("button",'onClick={() => handleRemoveFromList(list.id, item.symbol)} className="p-0.5 rounded opacity-0 group-hover:opacity-100 hover:bg-surface-600 text-gray-500 hover:text-red-400 transition-all"'))
c.append("                            "+st("X",'className="w-3 h-3"'))
c.append("                          "+ct("button"))
c.append("                        "+ct("div"))
c.append("                      ))}")
c.append("                    "+ct("div"))
c.append("                  )}")
c.append("")
c.append("                  "+ot("div",'className="mt-3 pt-3 border-t border-surface-700/50 flex items-center justify-between"'))
c.append("                    "+ot("span",'className="text-[10px] text-gray-500"')+"{list.items.length} item{list.items.length !== 1 ? 's' : ''}"+ct("span"))
c.append("                    "+ot("span",'className="text-[10px] text-gray-600"')+"Created {new Date(list.createdAt).toLocaleDateString()}"+ct("span"))
c.append("                  "+ct("div"))
c.append("                "+ct("div"))
c.append("              ))}")
c.append("            "+ct("div"))
c.append("          ) : !showNewList && (")
c.append("            "+ot("div",'className="card text-center py-12"'))
c.append("              "+st("List",'className="w-12 h-12 text-gray-600 mx-auto mb-4"'))
c.append("              "+ot("p",'className="text-lg text-gray-400 font-medium"')+"No lists yet"+ct("p"))
c.append("              "+ot("p",'className="text-sm text-gray-500 mt-1"')+"Create a list to organize and track custom groups of stocks"+ct("p"))
c.append("              "+ot("button",'onClick={() => setShowNewList(true)} className="mt-4 px-4 py-2 text-sm font-medium rounded-lg bg-primary-600 text-white hover:bg-primary-500 transition-colors"')+"Create Your First List"+ct("button"))
c.append("            "+ct("div"))
c.append("          )}")
c.append("        "+ct("div"))
c.append("      )}")
c.append("")
c.append("      {/* Suggested Lists Tab */}")
c.append("      {activeTab === 'suggested' && (")
c.append("        "+ot("div",'className="space-y-4"'))
c.append("          "+ot("p",'className="text-sm text-gray-400"')+"Popular stock combinations curated for common investment strategies. Click to add any of these to your lists."+ct("p"))
c.append("          "+ot("div",'className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4"'))
c.append("            {SUGGESTED_LISTS.map((suggested) => {")
c.append("              const IconComp = ICON_MAP[suggested.icon] || List")
c.append("              return (")
c.append("                "+ot("div",'key={suggested.id} className="card hover:border-primary-500/30 transition-colors"'))
c.append("                  "+ot("div",'className="flex items-start justify-between mb-3"'))
c.append("                    "+ot("div",'className="flex items-center gap-2"'))
c.append("                      "+ot("div",'className="w-8 h-8 rounded-lg bg-primary-600/20 flex items-center justify-center"'))
c.append("                        "+st("IconComp",'className="w-4 h-4 text-primary-400"'))
c.append("                      "+ct("div"))
c.append("                      "+ot("div"))
c.append("                        "+ot("h3",'className="text-sm font-semibold text-white"')+"{suggested.name}"+ct("h3"))
c.append("                        "+ot("p",'className="text-[11px] text-gray-500"')+"{suggested.items.length} stocks"+ct("p"))
c.append("                      "+ct("div"))
c.append("                    "+ct("div"))
c.append("                    "+ot("button",'onClick={() => handleCopySuggested(suggested)} className={'+BQ+'flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-lg border transition-all ${copiedId === suggested.id ? '+Q+'bg-green-600/20 border-green-500/50 text-green-300'+Q+' : '+Q+'border-surface-600 text-gray-400 hover:text-primary-300 hover:border-primary-500/50'+Q+'}'+BQ+'}'))
c.append("                      "+st("Copy",'className="w-3 h-3"'))
c.append("                      {copiedId === suggested.id ? 'Added!' : 'Add to My Lists'}")
c.append("                    "+ct("button"))
c.append("                  "+ct("div"))
c.append("                  "+ot("p",'className="text-xs text-gray-400 mb-3"')+"{suggested.description}"+ct("p"))
c.append("                  "+ot("div",'className="flex flex-wrap gap-1.5"'))
c.append("                    {suggested.items.map((item) => (")
c.append("                      "+ot("Link",'key={item.symbol} to={'+BQ+'/stock/${item.symbol}'+BQ+'} className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-surface-700/50 hover:bg-surface-600 text-xs font-mono transition-colors"'))
c.append("                        "+ot("span",'className="font-bold text-white"')+"{item.symbol}"+ct("span"))
c.append("                        "+ot("span",'className="text-gray-500 hidden sm:inline"')+"{item.name}"+ct("span"))
c.append("                      "+ct("Link"))
c.append("                    ))}")
c.append("                  "+ct("div"))
c.append("                "+ct("div"))
c.append("              )")
c.append("            })}")
c.append("          "+ct("div"))
c.append("        "+ct("div"))
c.append("      )}")
c.append("    "+ct("div"))
c.append("  )")
c.append("}")

with open(path,'w',encoding='utf-8') as f:
    f.write('\n'.join(c))
print('ListsPage.jsx written successfully')
